CREATE TABLE items (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Gender ENUM('Men', 'Women') NOT NULL,
    Quantity_XS INT DEFAULT 0,
    Quantity_S INT DEFAULT 0,
    Quantity_M INT DEFAULT 0,
    Quantity_L INT DEFAULT 0,
    Quantity_XL INT DEFAULT 0,
    ImageURL VARCHAR(255) DEFAULT NULL,
    user_id INT NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE categories (
    CategoryID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

ALTER TABLE items
ADD COLUMN CategoryID INT,
ADD FOREIGN KEY (CategoryID) REFERENCES categories(CategoryID);