CREATE TABLE items (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Gender ENUM('Men', 'Women') NOT NULL,
    Size ENUM('XS', 'S', 'M', 'L', 'XL') NOT NULL,
    Quantity INT NOT NULL,
    ImageURL VARCHAR(255) DEFAULT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

ALTER TABLE items ADD COLUMN user_id INT NOT NULL;